# Сохраняем пароль от микротиков в локальную переменную на localhost
- name: Set mikrotik username && password
  hosts: localhost
  vars_prompt:
    - name: MIKROTIK_PASSWORD
      private: true
  tasks:
    - set_fact:
        MIKROTIK_USERNAME: "admin"
        MIKROTIK_PASSWORD: "{{ MIKROTIK_PASSWORD }}"

# Синхронизируем стандартные для всех микротиков настройки
- name: Mikrotik default
  gather_facts: no
  hosts: localhost
  vars:
    MIKROTIK_HOSTS:
      - "sw1.home2.vs"
      - "sw1.hl.vs"
    MIKROTIK_DNS:
      - name: "sw1.home2.vs"
        address: "10.29.0.1"
      - name: "sw1.hl.vs"
        address: "10.30.10.1"
      - name: "pve1.hl.vs"
        address: "10.30.10.10"
      - name: "docker1.hl.vs"
        address: "10.30.11.10"
      - name: "frigate.hl.vs"
        address: "10.30.11.11"

      # Old network settings
      - name: "veranda.cams.dacha.vs"
        address: "10.10.5.2"
      - name: "mangal.cams.dacha.vs"
        address: "10.10.5.3"
      - name: "car.cams.dacha.vs"
        address: "10.10.5.4"
      - name: "tualet.cams.dacha.vs"
        address: "10.10.5.5"
      - name: "lift.cams.home1.vs"
        address: "10.10.2.2"
  roles:
    - mikrotik-default-security
    - mikrotik-dns-sync

## Синхронизируем настройки микротиков участвующих в OSPF маршрутизации
#- name: Mikrotik OSPF
#  gather_facts: no
#  hosts: localhost
#  vars:
#    MIKROTIK_HOSTS:
#      - "sw1.home2.vs"
#      - "sw1.hl.vs"
#  roles:
#    - mikroitk-default-ospf