- name: Mikrotik sync
  gather_facts: no
  hosts: localhost
  vars:
    MIKROTIK_HOSTS:
      - "sw1.home2.vs"
      - "sw1.hl.vs"
    MIKROTIK_DNS:
      - name: "sw1.home2.vs"
        address: "10.29.0.1"
      - name: "sw1.hl.vs"
        address: "10.30.10.1"
      - name: "pve1.hl.vs"
        address: "10.30.10.10"
      - name: "docker1.hl.vs"
        address: "10.30.11.10"
      - name: "frigate.hl.vs"
        address: "10.30.11.11"

      # Old network settings
      - name: "veranda.cams.dacha.vs"
        address: "10.10.5.2"
      - name: "mangal.cams.dacha.vs"
        address: "10.10.5.3"
      - name: "car.cams.dacha.vs"
        address: "10.10.5.4"
      - name: "tualet.cams.dacha.vs"
        address: "10.10.5.5"
      - name: "lift.cams.home1.vs"
        address: "10.10.2.2"
  vars_prompt:
    - name: MIKROTIK_PASSWORD
      private: true
  roles:
    - mikroitk-default-security
    - mikroitk-dns-sync
